services:
  web:
    container_name: gazzzetka
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    command: ["python", "DjangoGazzzetka/manage.py", "runserver", "0.0.0.0:8000"]

  db:
    image: postgres:14
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    image: redis:latest
    restart: always

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A DjangoGazzzetka worker --loglevel=info
    depends_on:
      - redis
      - db
    volumes:
      - .:/app
    env_file:
      - .env

volumes:
  postgres_data:
